services:
    oro_debug.database.isolation.process_executor:
        public: false
        class: 'Gorgo\Bundle\PlatformDebugBundle\Service\Database\ProcessExecutor'

    oro_debug.database.isolation.isolator.pdo_mysql:
        class: 'Gorgo\Bundle\PlatformDebugBundle\Isolator\Database\MysqlDatabaseIsolator'
        arguments:
            - '@oro_debug.database.isolation.process_executor'
        tags:
            - {name: oro.database.isolator, alias: pdo_mysql}

    oro_debug.database.isolation.isolator.pdo_pgsql:
        class: 'Gorgo\Bundle\PlatformDebugBundle\Isolator\Database\PgsqlDatabaseIsolator'
        arguments:
            - '@oro_debug.database.isolation.process_executor'
        tags:
            - {name: oro.database.isolator, alias: pdo_pgsql}

    oro_debug.database.isolation.isolator.registry:
        class: 'Gorgo\Bundle\PlatformDebugBundle\Service\Database\IsolatorRegistry'
        #TODO : replace with compiller pass with priorities
        calls:
            - ['addIsolator',['@oro_debug.database.isolation.isolator.pdo_mysql', 'pdo_mysql']]
            - ['addIsolator',['@oro_debug.database.isolation.isolator.pdo_pgsql', 'pdo_pgsql']]
