services:
    gorgo.oro_message_queue.consumption.container_reset_extension:
        class: 'Gorgo\Bundle\PlatformDebugBundle\MessageQueue\Extension\DisableContainerResetExtension'
        parent: oro_message_queue.consumption.container_reset_extension
        decorates: 'oro_message_queue.consumption.container_reset_extension'
        public: false
