imports:
    - { resource: 'workflow_services.yml', ignore_errors: true }
    - { resource: 'action_services.yml', ignore_errors: true }
    - { resource: 'database_services.yml', ignore_errors: true }
    - { resource: 'message_queue.yml', ignore_errors: true }
    - { resource: 'client.yml', ignore_errors: true }

services:

    gorgo.fixtures.yml_parser:
        class: 'Gorgo\Bundle\PlatformDebugBundle\Fixtures\GorgoYamlParser'
        calls:
            - [setKernel, ['@kernel']]
